name: Trigger PR in PMS on release
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dispatch an update
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: 'mollux/repository_dispatch_dest'
          event-type: update_event
